import { useEffect, useState } from 'react';
import { api } from '../api';
import { MiniLine, PageHeader, Panel, SectionTitle, StatCard } from '../ui.jsx';
const ROUTE_OPTIONS=['ALL','DEL-BOM','DEL-BLR','BOM-BLR','DEL-CCU','MAA-DEL','BLR-HYD'];
const money=v=>v==null?'N/A':`₹${Math.round(v).toLocaleString('en-IN')}`;
export default function LeadTime(){const [route,setRoute]=useState('ALL');const [data,setData]=useState(null);const [error,setError]=useState(null);useEffect(()=>{setData(null);api.getLeadTime(route==='ALL'?undefined:route).then(setData).catch(e=>setError(e.message))},[route]);if(error)return <div className="error-box">{error}</div>;return <><PageHeader kicker="Booking horizon" title="Lead-Time Analysis" subtitle="Fare by booking window (T+1 … T+45), from real collected observations" right={<select value={route} onChange={e=>setRoute(e.target.value)}>{ROUTE_OPTIONS.map(r=><option key={r}>{r}</option>)}</select>}/><div className="notice"><strong>Descriptive view.</strong> Median fares are compared by booking window for the selected quote date. This is not a causal or predictive elasticity estimate.</div>{!data?<div className="muted" style={{marginTop:16}}>Loading lead-time data…</div>:<>
  <div className="kpi-grid" style={{gridTemplateColumns:'repeat(5,minmax(0,1fr))'}}>{data.windows.map(w=><StatCard key={w.window} label={w.window} value={money(w.median_fare)} hint={`${w.observation_count} observations`} tone={w.window==='T+45'?'gold':''}/>)}</div>
  <div className="detail-grid"><Panel><SectionTitle title="Median fare by booking window" subtitle="Current descriptive profile"/><MiniLine values={data.windows.map(w=>w.median_fare)} labels={data.windows.map(w=>w.window)} color="#3fb7ff" ariaLabel="Median fare by booking window"/></Panel>
  <Panel><SectionTitle title="Key context"/><div className="detail-list"><div><span>Selected route</span><strong>{route}</strong></div><div><span>Highest observed median</span><strong>{money(Math.max(...data.windows.map(w=>w.median_fare||0)))}</strong></div><div><span>Lowest observed median</span><strong>{money(Math.min(...data.windows.filter(w=>w.median_fare!=null).map(w=>w.median_fare)))}</strong></div></div></Panel></div>
  <Panel><SectionTitle title="Window detail"/><table><thead><tr><th>Booking window</th><th>Median fare</th><th>Observations</th></tr></thead><tbody>{data.windows.map(w=><tr key={w.window}><td>{w.window}</td><td>{money(w.median_fare)}</td><td>{w.observation_count}</td></tr>)}</tbody></table></Panel>
 </>}</>}
